CREATE TABLE SINGER
(
    ID         SERIAL,
    FIRST_NAME VARCHAR(60) NOT NULL,
    LAST_NAME  VARCHAR(40) NOT NULL,
    BIRTH_DATE DATE,
    UNIQUE (FIRST_NAME, LAST_NAME),
    PRIMARY KEY (ID)
);
CREATE TABLE ALBUM
(
    ID           SERIAL,
    SINGER_ID    INT          NOT NULL,
    TITLE        VARCHAR(100) NOT NULL,
    RELEASE_DATE DATE,
    UNIQUE (SINGER_ID, TITLE),
    PRIMARY KEY (ID),
    CONSTRAINT FK_ALBUM FOREIGN KEY (SINGER_ID)
        REFERENCES SINGER (ID)
);

